"""Settings module"""

FORFEIT = True
FORFEIT_TIME = 10*60  # Time in seconds
LEAGUE_CLIENT_PATH = r'C:\\Riot Games\\League of Legends' # Replace None with your path. Ex: 'C:\\Riot Games\\League of Legends'
TESSERACT_PATH = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

## Messages
if FORFEIT:
 STARTGAME_MESSAGE: str = f"BOT ENABLED! GOOD LUCK! FORFEIT ENABLE! FORFEITING AFTER {FORFEIT_TIME} SECONDS"
else:
 STARTGAME_MESSAGE: str = f"BOT ENABLED! GOOD LUCK! FORFEIT DISABLE!"
FORFEIT_AFTER: str = f"FORFEITING AFTER {FORFEIT_TIME} SECONDS"
FORFEIT_MESSAGE: str = f"CYA! BOT FORFEITING"
CREFITS_MESSAGE: str = f"BOT MADE BY JFD02, CUSTOMIZED BY WUZENLIZ"
DOWNLOAD_MESSAGE: str = f"DOWNLOAD THE BOT HERE: https://github.com/jfd02/TFT-OCR-BOT.git"

SPAM_ENABLED = True
# In clude ton of trash talk, distrubing messages, and other stuff
SPAM_LIST = {
 0: f"SHOUT OUT TO KHANHSAC! SUBCRIBE TO HIM!",
 1: f"HMMMMM! YUMMY!",
 2: f"YUMMY!",
 3: f"NINCE BREAD!",
 4: f"SUBCRIBE TO KHANHSAC!",
 5: f"SUBCRIBE TO JFD02!",
 6: f"SUBCRIBE TO WUZENLIZ!",
 7: f"MUA KHO GA O MIXIFOOD",
 8: f"GG!",
 9: f"GGWP!",
 10: f"GG EZ!",
 11: f"WHAT A NICE GAME!",
 12: f"IS THIS 200YRS OF BALANCE?",
 13: f"RITO PLS!",
 14: f"RITO PLS FIX!",
 15: f"RITO PLS FIX THIS GAME!",
 16: f"RITO PLS FIX THIS GAME! IT'S SO UNBALANCED!",
 17: f"PRODUCTED BY RITO ENTERTAINMENT",
 18: f"PRODUCTED WITH 200YRS OF BALANCE",
 19: f"200YRS OF BALANCE!",
 20: f"WHAT WAS THAT? 200YRS OF BALANCE?",
 21: f"WHAT WAS THAT? 200YRS OF BALANCE? I DON'T THINK SO!",
}